version: '2'

services:
  redis:
    build: ./redis
    image: redcarpet/redcarpet-redis
    container_name: redis
    logging:
        driver: journald
    volumes:
      - /redis
  postgres:
    image: postgres
    container_name: postgres
    environment:
    - POSTGRES_USER:redcarpetweb
    - POSTGRES_PASSWORD:redcarpetweb123
    - POSTGRES_DB:web_new_development
    volumes:
     - /postgres:/var/lib/postgresql/data
  stunnel:
    build: ./stunnel
    image: redcarpet/redcarpet-stunnel
    container_name: stunnel
    depends_on:
      - postgres
    logging:
        driver: journald
  pgbouncer:
    build: ./pgbouncer
    image: redcarpet/redcarpet-pgbouncer
    container_name: pgbouncer
    ports:
    - "6000:6000"
    depends_on:
      - postgres
      - stunnel
    logging:
        driver: journald
  rqscheduler:
    build: ./rqscheduler
    image: redcarpet/redcarpet-rqscheduler
    container_name: rqscheduler
    depends_on:
      - redis
    logging:
        driver: journald
  rqworker:
    build: ./rqworker
    image: redcarpet/redcarpet-rqworker
    container_name: rqworker
    depends_on:
      - redis
      - postgres
      - stunnel
      - pgbouncer
    logging:
        driver: journald
  flask:
    build: ./flask
    image: redcarpet/redcarpet-flask
    container_name: flask
    depends_on:
      - redis
      - postgres
      - stunnel
      - pgbouncer
    logging:
        driver: journald
  nginx:
    build: ./nginx
    image: redcarpet/redcarpet-nginx
    container_name: nginx
    depends_on:
      - flask
    logging:
        driver: journald