apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flask
  namespace: flask
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: flask
      name: flask
    spec:
      containers:
      - name: flask
        image: redcarpet/redcarpet-pgbouncer
        imagePullPolicy: Never
        ports: 
          - containerPort: 9001
            name: flask_uwsgi