apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  namespace: test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: nginx
      name: nginx
    spec:
    hostnetwork: true
      containers:
      - name: nginx
        image: redcarpet/redcarpet-nginx
        imagePullPolicy: Never
        ports: 
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https