apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  namespace: test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: redis
      name: redis
    spec:
      containers:
      - name: redis
        image: rediscarpet/rediscarpet-redis
        imagePullPolicy: Never
        ports: 
          - containerPort: 6379
            name: redis
        volumeMounts:
          - name: redis
            mountPath: /redisis
      volumes:
      - name: redis
        emptyDir: {}