apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-proxy
  namespace: test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: nginx-proxy
      name: nginx-proxy
    spec:
      containers:
      - name: nginx-proxy
        image: redcarpet/redcarpet-reverse-proxy
        imagePullPolicy: Never
        ports: 
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https