apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: flask
  name: flask
  namespace: test
spec: 
  ports:
    - port: 9001
      name: flask
  # label keys and values that must match in order to receive traffic for this service
  selector: 
    name: flask