apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: nginx
  name: nginx
  namespace: test
spec: 
  ports:
    - port: 80
      name: nginx
    - port: 443
      name: nginx-https
  # label keys and values that must match in order to receive traffic for this service
  selector: 
    name: nginx