apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: redis
  name: redis
  namespace: test
spec: 
  ports:
    - port: 6379
      name: redis
  # label keys and values that must match in order to receive traffic for this service
  selector: 
    name: redis